# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8, 3.9, "3.10"]
        include:
        # custom tests
        - python-version: "3.11-dev"
          os: ubuntu-latest
          experimental: true
          allowed_failure: true
        - python-version: pypy3
          os: ubuntu-latest
          experimental: true
          allowed_failure: true
        - os: macos-latest
          python-version: 3.7
        - os: windows-latest
          python-version: 3.7
          experimental: true
          allowed_failure: true
    steps:
    # Python and pip setup
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip
      run: python -m pip install --upgrade pip setuptools wheel

    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"

    - name: pip cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # package setup
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: python -m pip install -e "."

    # tests
    - name: Test with pytest
      run: |
        python -m pip install pytest pytest-cov
        pytest --cov=./
